version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 9001:9001
    container_name: sample_app
    volumes:
      - ./:/go
    tty: true
    restart: always
    depends_on:
      - db

  db:
    image: sample-api-db
    container_name: sample-api-db
    build: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: katsukiniwa-password
      TZ: "UTC"
    ports:
      - "127.0.0.1:3306:3306"
