version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 9001:9001
    container_name: sample_app
    volumes:
      - ./:/go
    tty: true
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASS: password
      DB_HOST: sample-api-db
      DB_PORT: 3306
      DB_NAME: ent_sample

  db:
    # image: sample-api-db
    container_name: sample-api-db
    build: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "UTC"
    ports:
      - 3306:3306
