// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from injecter.go:

func initMovieRepository(fileName string) *MovieRepository {
	movieFinder := NewColonDelimitedMovieFinder(fileName)
	movieRepository := NewMovieRepository(movieFinder)
	return movieRepository
}
